exclude: ["README.md"]
pygments: true
markdown: redcarpet
auto: false
title: kurtlau的记事本
site_url: kurtliu.github.com
permalink: /:year/:month/:day/:title
author:
  name: Kurtlau
categories_path: /categories.html
tags_path: /tags.html
rss_path: /rss.xml
comments:
  provider: disqus
  youyan:
    userid: 1763001
  disqus:
    shortname: kurtlau
analytics:
  provider: google 

